FROM pseudo-refmap AS test
COPY tests/test_catalog.fa.gz /reference/catalog.fa.gz
COPY tests/test_samples/ /samples/
COPY tests/popmap_test /popmap
COPY tests/test_realigned /expected_realigned
COPY tests/test_populations/populations.snps.vcf expected_populations.snps.vcf

COPY tests/run_test.sh /

RUN chmod +x run_test.sh

CMD ["./run_test.sh"]
